In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
df = pd.read_parquet('./data/processed/price_data_btc.parquet')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_timestamp  1000 non-null   datetime64[ns]
 1   open-usd         1000 non-null   float64
 2   1b. open (USD)   1000 non-null   object
 3   high-usd         1000 non-null   float64
 4   2b. high (USD)   1000 non-null   object
 5   low-usd          1000 non-null   float64
 6   3b. low (USD)    1000 non-null   object
 7   close-usd        1000 non-null   float64
 8   4b. close (USD)  1000 non-null   object
 9   volume           1000 non-null   float64
 10  market-cap       1000 non-null   float64
dtypes: datetime64[ns](1), float64(6), object(4)
memory usage: 86.1+ KB

In [22]:
df.head(20)

,event_timestamp,open-usd,1b. open (USD),high-usd,2b. high (USD),low-usd,3b. low (USD),close-usd,4b. close (USD),volume,market-cap
event_id,,,,,,,,,,,
0,2023-01-11,17440.64,17440.64000000,17510.00,17510.00000000,17428.37,17428.37000000,17451.42,17451.42000000,14277.76355,14277.76355
1,2023-01-10,17179.04,17179.04000000,17499.00,17499.00000000,17146.34,17146.34000000,17440.66,17440.66000000,221382.42581,221382.42581
2,2023-01-09,17127.83,17127.83000000,17398.80,17398.80000000,17104.66,17104.66000000,17178.26,17178.26000000,266211.52723,266211.52723
3,2023-01-08,16943.83,16943.83000000,17176.99,17176.99000000,16911.00,16911.00000000,17127.83,17127.83000000,135155.89695,135155.89695
4,2023-01-07,16950.31,16950.31000000,16981.91,16981.91000000,16908.00,16908.00000000,16943.57,16943.57000000,104526.56880,104526.56880
5,2023-01-06,16831.85,16831.85000000,17041.00,17041.00000000,16679.00,16679.00000000,16950.65,16950.65000000,207401.28415,207401.28415
6,2023-01-05,16850.36,16850.36000000,16879.82,16879.82000000,16753.00,16753.00000000,16831.85,16831.85000000,163473.56641,163473.56641
7,2023-01-04,16675.65,16675.65000000,16991.87,16991.87000000,16652.66,16652.66000000,16850.36,16850.36000000,220362.18862,220362.18862
8,2023-01-03,16672.78,16672.78000000,16778.40,16778.40000000,16605.28,16605.28000000,16675.18,16675.18000000,159541.53733,159541.53733
9,2023-01-02,16617.17,16617.17000000,16799.23,16799.23000000,16548.70,16548.70000000,16672.87,16672.87000000,121888.57191,121888.57191
10,2023-01-01,16541.77,16541.77000000,16628.00,16628.00000000,16499.01,16499.01000000,16616.75,16616.75000000,96925.41374,96925.41374
11,2022-12-31,16607.48,16607.48000000,16644.09,16644.09000000,16470.00,16470.00000000,16542.40,16542.40000000,114490.42864,114490.42864
12,2022-12-30,16633.47,16633.47000000,16677.35,16677.35000000,16333.00,16333.00000000,16607.48,16607.48000000,164916.31174,164916.31174
13,2022-12-29,16547.32,16547.32000000,16664.41,16664.41000000,16488.91,16488.91000000,16633.47,16633.47000000,160998.47158,160998.47158
14,2022-12-28,16706.06,16706.06000000,16785.19,16785.19000000,16465.33,16465.33000000,16547.31,16547.31000000,193037.56577,193037.56577
15,2022-12-27,16919.39,16919.39000000,16972.83,16972.83000000,16592.37,16592.37000000,16706.36,16706.36000000,173749.58616,173749.58616
16,2022-12-26,16832.11,16832.11000000,16944.52,16944.52000000,16791.00,16791.00000000,16919.39,16919.39000000,124564.00656,124564.00656
17,2022-12-25,16835.73,16835.73000000,16857.96,16857.96000000,16721.00,16721.00000000,16832.11,16832.11000000,125441.07202,125441.07202
18,2022-12-24,16778.52,16778.52000000,16869.99,16869.99000000,16776.62,16776.62000000,16836.12,16836.12000000,100224.29096,100224.29096
19,2022-12-23,16821.90,16821.90000000,16955.14,16955.14000000,16731.13,16731.13000000,16778.50,16778.50000000,161612.00947,161612.00947

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   event_timestamp      1000 non-null   object
 1   1a. open (USD)       1000 non-null   object
 2   1b. open (USD)       1000 non-null   object
 3   2a. high (USD)       1000 non-null   object
 4   2b. high (USD)       1000 non-null   object
 5   3a. low (USD)        1000 non-null   object
 6   3b. low (USD)        1000 non-null   object
 7   4a. close (USD)      1000 non-null   object
 8   4b. close (USD)      1000 non-null   object
 9   5. volume            1000 non-null   object
 10  6. market cap (USD)  1000 non-null   object
dtypes: object(11)
memory usage: 86.1+ KB

In [23]:
df1 = pd.read_parquet('./data/processed/metric_data_btc.parquet')
df1.head()

,event_timestamp,blocks-size,avg-block-size,n-transactions-total,hash-rate,difficulty,transaction-fees-usd,n-unique-addresses,n-transactions,my-wallet-n-users,utxo-count,n-transactions-excluding-popular,estimated-transaction-volume-usd,trade-volume,total-bitcoins,market-price
event_id,,,,,,,,,,,,,,,,
0,2021-01-01,319114.048500,1.352233,601577750.0,1.377640e+08,1.859959e+13,1.455398e+06,609741.0,258080.0,6.346725e+07,6.952462e+07,255086.0,4.343208e+09,6.065241e+08,1.858715e+07,28982.56
1,2021-01-02,319315.580633,1.395637,601835959.0,1.396132e+08,1.859959e+13,2.504284e+06,711719.0,297111.0,6.354435e+07,6.931422e+07,293409.0,6.152237e+09,4.912580e+08,1.858814e+07,29393.75
2,2021-01-03,319526.405445,1.288694,602133929.0,1.460853e+08,1.859959e+13,2.893754e+06,812749.0,359116.0,6.363610e+07,6.929138e+07,355123.0,5.847743e+09,1.393907e+09,1.858913e+07,32195.46
3,2021-01-04,319729.832857,1.318806,602493027.0,1.599542e+08,1.859959e+13,3.516375e+06,851667.0,373734.0,6.373875e+07,6.928811e+07,368932.0,7.503148e+09,9.758314e+08,1.859012e+07,33000.78
4,2021-01-05,319957.982033,1.292713,602865747.0,1.451608e+08,1.859959e+13,3.677641e+06,845343.0,354091.0,6.384685e+07,6.933336e+07,349895.0,6.775408e+09,1.432013e+09,1.859122e+07,32035.03

In [26]:
df1.tail(12)

,event_timestamp,blocks-size,avg-block-size,n-transactions-total,hash-rate,difficulty,transaction-fees-usd,n-unique-addresses,n-transactions,my-wallet-n-users,utxo-count,n-transactions-excluding-popular,estimated-transaction-volume-usd,trade-volume,total-bitcoins,market-price
event_id,,,,,,,,,,,,,,,,
729,2022-12-31,445882.496807,1.071711,792239044.0,2.742413e+08,3.536407e+13,202082.967674,618594.0,242325.0,8.572223e+07,8.453833e+07,241915.0,1.461650e+09,8.571615e+07,1.924667e+07,16599.69
730,2023-01-01,446049.777365,0.842700,792482423.0,2.724834e+08,3.536407e+13,117878.596592,509337.0,187516.0,8.572750e+07,8.449416e+07,187194.0,9.603879e+08,6.796060e+07,1.924817e+07,16526.78
731,2023-01-02,446180.371298,1.021220,792669265.0,2.742413e+08,3.536407e+13,147534.494625,575250.0,229347.0,8.573253e+07,8.448543e+07,228933.0,1.181257e+09,4.010467e+07,1.924905e+07,16613.71
732,2023-01-03,446339.616331,1.248256,792897596.0,2.618835e+08,3.420907e+13,214074.294085,645565.0,272055.0,8.573865e+07,8.446857e+07,271592.0,1.935284e+09,4.084294e+07,1.925001e+07,16671.54
733,2023-01-04,446532.165942,1.224450,793170636.0,2.423565e+08,3.409357e+13,249884.053151,652878.0,277936.0,8.574552e+07,8.443300e+07,277455.0,2.477219e+09,6.712781e+07,1.925094e+07,16669.60
734,2023-01-05,446706.890340,1.155025,793447471.0,2.660837e+08,3.409357e+13,242153.007938,682119.0,279391.0,8.575242e+07,8.439924e+07,278919.0,2.113239e+09,8.870441e+07,1.925187e+07,16850.63
735,2023-01-06,446888.091119,1.052704,793726799.0,3.050641e+08,3.409357e+13,227037.365702,685990.0,276071.0,8.575938e+07,8.437475e+07,274971.0,1.512276e+09,6.158096e+07,1.925292e+07,16826.41
736,2023-01-07,447076.860037,0.956566,794002725.0,2.609993e+08,3.409357e+13,142863.893205,601071.0,246679.0,8.576597e+07,8.435814e+07,246219.0,1.008768e+09,7.780819e+07,1.925397e+07,16951.97
737,2023-01-08,447225.168643,0.905175,794250302.0,2.593045e+08,3.409357e+13,115008.446256,565595.0,228488.0,8.577250e+07,8.437813e+07,228060.0,7.486567e+08,2.472915e+07,1.925493e+07,16945.20
738,2023-01-09,447363.592726,1.235484,794478869.0,2.576097e+08,3.409357e+13,187503.110141,662916.0,287347.0,8.577943e+07,8.443495e+07,286843.0,1.764694e+09,3.900119e+07,1.925589e+07,17108.41
739,2023-01-10,447551.392077,1.378499,794766348.0,2.864213e+08,3.409357e+13,193856.168399,695664.0,302809.0,8.578616e+07,8.441261e+07,302322.0,1.816231e+09,1.016320e+08,1.925689e+07,17192.07
741,2023-01-11,447551.392077,1.378499,794766348.0,2.864213e+08,3.409357e+13,193856.168399,695664.0,302809.0,8.578616e+07,8.432967e+07,302322.0,1.816231e+09,7.759734e+07,1.925747e+07,17443.68

In [5]:
from feast import FeatureStore
from datetime import datetime
store = FeatureStore(repo_path="./data/feature_repo/")

In [7]:
chart_df = pd.read_parquet('./data/processed/metric_data_btc.parquet')
timestamps = pd.date_range(
    end=pd.Timestamp.now(), 
    periods=len(chart_df), 
    freq='D').to_frame(name="event_timestamp", index=False)

entity_df = pd.DataFrame.from_dict(
    {
        "event_timestamp": [
        ],
    }
)
entity_df = pd.concat(objs=[entity_df, timestamps])

# entity_df["event_timestamp"] = pd.to_datetime("now", utc=True)

#entity_sql = f"""
#    SELECT *
#    FROM {store.get_data_source("daily_bitcoin_metric_source").get_table_query_string()}
#    WHERE event_timestamp BETWEEN '2022-10-01' and '2022-12-24'
#"""

#print(store.get_feature_service("daily_bitcoin_v1"))
print(entity_df.head())
training_df = store.get_historical_features(
    entity_df=entity_df,
    features=store.get_feature_service("daily_bitcoin_v1"),
).to_df()
training_df.head()

             event_timestamp
0 2021-01-10 20:19:39.669738
1 2021-01-11 20:19:39.669738
2 2021-01-12 20:19:39.669738
3 2021-01-13 20:19:39.669738
4 2021-01-14 20:19:39.669738

,event_timestamp,blocks-size,avg-block-size,n-transactions-total,hash-rate,difficulty,transaction-fees-usd,n-unique-addresses,n-transactions,my-wallet-n-users,...,estimated-transaction-volume-usd,trade-volume,total-bitcoins,market-price,open-usd,high-usd,low-usd,close-usd,volume,market-cap
0,2021-01-10 20:19:39.669738+00:00,320970.191524,1.282691,604699941.0,1.628797e+08,2.060742e+13,3.643195e+06,768365.0,331865.0,6.433912e+07,...,4.278195e+09,7.114748e+08,1.859617e+07,40240.72,40088.22000000,41350.00000000,35111.11000000,38150.02000000,118209.54450300,118209.54450300
1,2021-01-11 20:19:39.669738+00:00,321174.048974,1.337251,605031340.0,1.577576e+08,2.060742e+13,4.563809e+06,801285.0,333958.0,6.442876e+07,...,6.926937e+09,1.415451e+09,1.859715e+07,38240.09,38150.02000000,38264.74000000,30420.00000000,35404.47000000,251156.13828700,251156.13828700
2,2021-01-12 20:19:39.669738+00:00,321380.113784,1.324212,605365473.0,1.516112e+08,2.060742e+13,5.843154e+06,796457.0,336627.0,6.451925e+07,...,7.357383e+09,3.039065e+09,1.859814e+07,35544.94,35410.37000000,36628.00000000,32531.00000000,34051.24000000,133948.15199600,133948.15199600
3,2021-01-13 20:19:39.669738+00:00,321576.046068,1.264866,605701559.0,1.557088e+08,2.060742e+13,4.725848e+06,772596.0,319167.0,6.460234e+07,...,5.277220e+09,1.344114e+09,1.859902e+07,34011.82,34049.15000000,37850.00000000,32380.00000000,37371.38000000,124477.91493800,124477.91493800
4,2021-01-14 20:19:39.669738+00:00,321768.180950,1.296483,606020714.0,1.505868e+08,2.060742e+13,5.760123e+06,802110.0,338809.0,6.468861e+07,...,8.352712e+09,1.209078e+09,1.859989e+07,37393.13,37371.38000000,40100.00000000,36701.23000000,39144.50000000,102950.38942100,102950.38942100

In [12]:
feature_service = store.get_feature_service("daily_bitcoin_v1")
feature_vector = store.get_online_features(
    features=feature_service,
    entity_rows=[
        # {join_key: entity_value}
        #{"event_timestamp": datetime(2021, 4, 12, 10, 59, 42),},
    ],
).to_dict()
print(feature_vector)

TypeError: get_online_features() missing 1 required positional argument: 'entity_rows'